name: Deploy Preprod

on:
  push:
    branches:
      - develop

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Commit build assets
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add public/build

          if ! git diff --cached --quiet; then
            git commit -m "auto build assets [skip ci]"
            git push
          fi

      - name: Trigger deployment webhook
        run: |
          if [ -z "${{ secrets.WEBHOOK_URL }}" ]; then
            echo "ERROR: WEBHOOK_URL secret is missing or empty."
            exit 1
          fi
          if [ -z "${{ secrets.WEBHOOK_TOKEN }}" ]; then
            echo "ERROR: WEBHOOK_TOKEN secret is missing or empty."
            exit 1
          fi
          curl -X POST "${{ secrets.WEBHOOK_URL }}" \
          -H "X-Deploy-Token: ${{ secrets.WEBHOOK_TOKEN }}"
