name: Deploy preproduction

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupère le code source
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Installe les dépendances PHP
        run: composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Installe les dépendances frontend
        run: npm ci

      - name: Build les assets frontend
        run: npm run build

      - name: Deploiement des fichiers avec FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftps
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          local-dir: ./
          security: loose
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
            **/tests/**
            **/.env
            **/.env.*
            **/storage/logs/**
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/storage/framework/testing/**
            **/storage/framework/views/**
            **/Dockerfile
            **/Dockerfile.prod
            **/docker-compose.yml
            **/docker-compose.prod.yml
            **/.dockerignore
            **/README.md
